# -*- coding: utf-8 -*-
"""Sistemas Nebulosos - kmeans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O6IPam4NWP2b4vUNNqdAa1i4KgA-fVwy
"""

import random
import numpy as np
import scipy
import scipy.spatial
import matplotlib.pyplot as plt

X = -2 * np.random.rand(150,2)
X1 = 1 + 2 * np.random.rand(50,2)
X2 = 3 + 5*np.random.rand(50,2)
X[50:100, :] = X1
X[100:150, :] = X2
plt.scatter(X[ : , 0], X[ :, 1], s = 50, c = 'b')
plt.show()


k = 4 #número de grupos
n = len(X)
u = np.zeros((n,k))
idx = np.zeros((n,1))
for i in range(n):
  rnd = random.randint(0,k-1)
  u[i,rnd] = 1
  idx[i] = rnd
  
  
w = np.zeros((k,1))
for i in range(k):
  
  ind = []
  for j in range(len(idx)):
    if i == idx[j]:
      ind.append(j)
  cluster = X[ind,:]
  w[i] = (1/len(ind))*sum(scipy.spatial.distance.pdist(cluster, 'euclidean'))
J = []
J.append(sum(w))

cluster_antigo = cluster
changes = True
iter = 1

while changes:
  individuos = []
  centroids = np.zeros((k,2))
  idx = np.zeros((n,1))
  for i in range(k):
    Gj = u[:,i]
    ind = []
    for j in range(len(Gj)):
      if Gj[j] == 1:
        ind.append(j)
    Xj = X[ind,:]
    individuos.append(Xj)
    centroids[i,:] = np.mean(Xj,0)
  #print(centroids)
  
  u = np.zeros((n,k))
  for i in range(n):
    dist = []
    for j in range(k):
      dist.append((X[i,0]-centroids[j,0])**2 + (X[i,1]-centroids[j,1])**2)
    rnd = dist.index(min(dist))
    u[i,rnd] = 1
    idx[i] = rnd

  w = np.zeros((k,1))
  for i in range(k):

    ind = []
    for j in range(len(idx)):
      if i == idx[j]:
        ind.append(j)
    cluster = X[ind,:]
    w[i] = (1/len(ind))*sum(scipy.spatial.distance.pdist(cluster, 'euclidean'))
  J.append(sum(w))
  
  cores = ['r*', 'g*', 'y*', 'c*', 'm*']
  for i in range(k):
      plt.plot(individuos[i][:, 0], individuos[i][:, 1], cores[i])
  plt.plot(centroids[:, 0], centroids[:, 1], 'ko')
  plt.show()

  if np.array_equal(cluster_antigo, cluster):
    changes = False
  else:
    cluster_antigo = cluster
    iter+=1